export const GET_HOME_DATA_EPIC = 'GET_HOME_DATA_EPIC';
export const GET_HOME_DATA_SUCCESS = 'GET_HOME_DATA_SUCCESS';
export const GET_HOME_DATA_ERROR = 'GET_HOME_DATA_ERROR';
export const GET_HOME_DATA_LOADING = 'GET_HOME_DATA_LOADING';
export const GET_HOME_DATA_CANCEL = 'GET_HOME_DATA_CANCEL';

export const SET_TRANSACTION_RECORD = 'SET_TRANSACTION_RECORD';
export const SET_DEDUCT_AMOUNT_USER = 'SET_DEDUCT_AMOUNT_USER';
export const FILTER_TRANSACTION_RECORD = 'FILTER_TRANSACTION_RECORD';
